# Generated by Django 3.2.21 on 2023-09-12 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModelOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='ColourOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EngineCapacityOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EngineLayoutOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_layout', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='YearOfManafactureOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_manufacture', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='blank', max_length=120)),
                ('manufacturer', models.CharField(default='blank', max_length=120)),
                ('car_model', models.CharField(default='blank', max_length=180)),
                ('engine_layout', models.CharField(default='blank', max_length=20)),
                ('engine_capacity', models.CharField(default='blank', max_length=20)),
                ('colour', models.CharField(default='blank', max_length=30)),
                ('year_of_manufacture', models.CharField(default='0000', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
