# Generated by Django 3.2.21 on 2023-09-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seats',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
