# Generated by Django 3.2.21 on 2023-09-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='collective.shape'),
        ),
    ]
