# Generated by Django 3.2.21 on 2023-10-15 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0005_auto_20231014_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=540),
            preserve_default=False,
        ),
    ]
