# Generated by Django 3.2.21 on 2023-10-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0006_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='drivetrain',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='fuel_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='gearbox',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='shape',
            field=models.CharField(max_length=20),
        ),
    ]
