# Generated by Django 3.2.21 on 2023-10-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
