# Generated by Django 3.2.21 on 2023-10-18 20:17

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0010_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=image_optimizer.fields.OptimizedImageField(upload_to='car-collective/media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='car-collective/media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='car-collective/media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_4',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='car-collective/media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_5',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='car-collective/media/'),
        ),
    ]
